### ISSUE TITLE
Embedded goahead 4.1.3 wopenAlloc call fails to compile - error C2065: 'WEBS_USE_MALLOC': undeclared identifier

### ISSUE THREAD

**Issue by buzz3791** [embedthis/goahead-gpl#4]
### Environment

1. O/S Version: Windows 10

2. GoAhead Version: 4.1.3

3. Hardware: N/A

### Build

N/A

### Problem Description:

When trying to embed goahead a call like the following fails to compile:

`wopenAlloc( NULL, (60 * 1024), WEBS_USE_MALLOC );`

This line results in this compiler error:

error C2065: 'WEBS_USE_MALLOC': undeclared identifier

Inspecting goahead.h it seems that WEBS_USE_MALLOC is only defined when ME_GOAHEAD_REPLACE_MALLOC is defined.  This seems like an error.  I want to use malloc but I can't tell wopenAlloc to use malloc unless I define ME_GOAHEAD_REPLACE_MALLOC .

**Comment by dev-embedthis** [comment]
The WEBS_USE_MALLOC means to use the GoAhead memory allocator and fall back to malloc when more memory is required. Without WEBS_USE_MALLOC, it means that GoAhead will be pre-provisioned with a memory block and will never call malloc. This is ideal for very memory constrained devices.

**Comment by buzz3791** [comment]
Thanks for the clarification.
